version: "{build}"
clone_depth: 10

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 15
      ARCH: amd64

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 10
  - ps: Restart-Computer

install:
  - if "%VS_VERSION%" == "15" if "%ARCH%" == "x86" set VS2017_X86=TRUE
  - if "%VS_VERSION%" == "15" if "%ARCH%" == "amd64" set VS2017_AMD64=TRUE
  - if "%VS2017_X86%" == "TRUE"
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if "%VS2017_AMD64%" == "TRUE"
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if not "%VS_VERSION%" == "15"
      call
      "C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\vcvarsall.bat"
      %ARCH%
  - chcp 65001
  - set INSTALL_FOLDER_NAME=インストール
  - ps: $Env:TEST_INSTALL_FOLDER = (Join-Path $Env:APPVEYOR_BUILD_FOLDER $Env:INSTALL_FOLDER_NAME)

build_script:
  - set PATH=C:\Ruby25-x64\bin;%PATH%
  - set CMAKE_GENERATOR_NAME=Visual Studio %VS_VERSION%
  - if "%VS_VERSION%" == "15"
      set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_NAME% 2017
  - if "%ARCH%" == "amd64"
      set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_NAME% Win64
  - set
  - cmake . -G "%CMAKE_GENERATOR_NAME%"
      -DCMAKE_INSTALL_PREFIX=%TEST_INSTALL_FOLDER%
  - cmake --build . --config RelWithDebInfo
  - cmake --build . --config RelWithDebInfo --target Install

before_test:
  - git clone --depth 1
      https://github.com/groonga/groonga.git
  - git clone --depth 1
      https://github.com/groonga/grntest.git
      groonga\test\command\grntest
  - cd groonga\test\command\grntest
  - bundle install --binstubs=..\bin
  - cd ..\..\..\..
  - del groonga\test\command\suite\select\filter\equal\vector_element_float.test
  - ps: Start-FileDownload 'https://packages.groonga.org/windows/groonga/groonga-9.0.0-x64.zip'
  - 7z x groonga-9.0.0-x64.zip
  - mv groonga-9.0.0-x64 %TEST_INSTALL_FOLDER%
  - ps: $Env:GROONGA_INSTALL_FOLDER = (Join-Path $Env:TEST_INSTALL_FOLDER groonga-9.0.0-x64)
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/kenhys/appveyor-langpack/command-line/command_runner.rb'
  - copy /Y command_runner.rb groonga\test\command_line\helper\
  - copy /Y run-test.rb groonga\test\command_line\

test_script:
  - set PATH=%GROONGA_INSTALL_FOLDER%\bin;%PATH%
  - set
  - ruby groonga\test\command_line\run-test.rb
     --groonga-install-prefix=C:\projects\appveyor-langpack\\u7E67\uFF64\u7E5D\uFF73\u7E67\uFF79\u7E5D\u533B\u30FB\u7E5D\uFF6B\groonga-9.0.0-x64

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
