version: "{build}"
clone_depth: 10

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_VERSION: 16
      ARCH: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 15
      ARCH: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: 14
      ARCH: amd64
    - VS_VERSION: 12
      ARCH: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_VERSION: 16
      ARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 15
      ARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: 14
      ARCH: x86
    - VS_VERSION: 12
      ARCH: x86

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 10
  - ps: Restart-Computer

install:
  - set PATH=C:\Ruby25-x64\bin;%PATH%
  - if "%VS_VERSION%" == "16" set VS_YEAR=2019
  - if "%VS_VERSION%" == "15" set VS_YEAR=2017
  - if %VS_VERSION% geq 15 if "%ARCH%" == "x86"
      call "C:\Program Files (x86)\Microsoft Visual Studio\%VS_YEAR%\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if %VS_VERSION% geq 15 if "%ARCH%" == "amd64"
      call "C:\Program Files (x86)\Microsoft Visual Studio\%VS_YEAR%\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %VS_VERSION% lss 15
      call
      "C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\vcvarsall.bat"
      %ARCH%
  - set INSTALL_FOLDER_NAME=インストール
  - ps: $Env:TEST_INSTALL_FOLDER = (Join-Path $Env:APPVEYOR_BUILD_FOLDER $Env:INSTALL_FOLDER_NAME)

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - choco install -y curl 7zip.commandline
  - git clone --depth https://github.com/groonga/groonga
  - curl -O http://packages.groonga.org/windows/groonga/groonga-9.0.6-x64.zip
  - 7z x groonga-9.0.6-x64.zip

before_test:
  - git clone --depth 1
      https://github.com/groonga/grntest.git
      test\command\grntest
  - cd test\command\grntest
  - bundle install --binstubs=..\bin
  - cd ..\..\..
  - del test\command\suite\select\filter\equal\vector_element_float.test

test_script:
  - set GRN_EXPR_OPTIMIZE=yes
  - ruby test\command\bin\grntest
     --groonga %APPVEYOR_BUILD_FOLDER%\..\groonga-9.0.6-x64\bin\groonga.exe
     --base-directory test\command
     --reporter mark
     --n-workers 2
     --timeout 60
     --read-timeout 30
     --n-retries 2
     test\command\suite

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
