version: "{build}"
clone_depth: 10

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 15
      ARCH: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: 14
      ARCH: amd64
    - VS_VERSION: 12
      ARCH: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 15
      ARCH: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: 14
      ARCH: x86
    - VS_VERSION: 12
      ARCH: x86

init:
  - ps: Set-WinSystemLocale ja-JP
  - ps: Start-Sleep -s 10
  - ps: Restart-Computer

install:
  - if "%VS_VERSION%" == "15" if "%ARCH%" == "x86" set VS2017_X86=TRUE
  - if "%VS_VERSION%" == "15" if "%ARCH%" == "amd64" set VS2017_AMD64=TRUE
  - if "%VS2017_X86%" == "TRUE"
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if "%VS2017_AMD64%" == "TRUE"
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if not "%VS_VERSION%" == "15"
      call
      "C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\vcvarsall.bat"
      %ARCH%
  - set INSTALL_FOLDER_NAME=install
  - ps: $Env:TEST_INSTALL_FOLDER = (Join-Path $Env:APPVEYOR_BUILD_FOLDER $Env:INSTALL_FOLDER_NAME)

build_script:
  - set CMAKE_GENERATOR_NAME=Visual Studio %VS_VERSION%
  - if "%VS_VERSION%" == "15"
      set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_NAME% 2017
  - if "%ARCH%" == "amd64"
      set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_NAME% Win64
  - set
  - cmake . -G "%CMAKE_GENERATOR_NAME%"
      -DCMAKE_INSTALL_PREFIX=%TEST_INSTALL_FOLDER%
  - cmake --build . --config RelWithDebInfo
  - cmake --build . --config RelWithDebInfo --target Install

on_success:
  - if "%VS_VERSION%" == "15" if "%ARCH%" == "amd64" (
      set /p REDIST_VERSION=<"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt";
      set VCREDIST_VCRUNTIME="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%REDIST_VERSION%\x64\Microsoft.VC141.CRT\vcruntime140.dll";
      set VCREDIST_MSVCP="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%REDIST_VERSION%\x64\Microsoft.VC141.CRT\msvcp140.dll";
    ) else (
      set /p REDIST_VERSION=<"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt";
      set VCREDIST_VCRUNTIME="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%REDIST_VERSION%\x86\Microsoft.VC141.CRT\vcruntime140.dll";
      set VCREDIST_MSVCP="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%REDIST_VERSION%\x86\Microsoft.VC141.CRT\msvcp140.dll";
    )
  - if "%VS_VERSION%" == "14" if "%ARCH%" == "amd64" (
      set VCREDIST_VCRUNTIME="C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\Redist\x64\vcruntime140.dll";
      set VCREDIST_MSVCP="C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\Redist\x64\msvcp140.dll";
    ) else (
      set VCREDIST_VCRUNTIME="C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\Redist\x86\vcruntime140.dll";
      set VCREDIST_MSVCP="C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\Redist\x86\msvcp140.dll";
    )
  - xcopy %VCREDIST_VCRUNTIME% %TEST_INSTLL_FOLDER%
  - xcopy %VCREDIST_MSVCP% %TEST_INSTLL_FOLDER%
  - set ARTIFACT=%TEST_INSTALL_FOLDER%-vcruntime.zip
  - 7z a %ARTIFACT% %TEST_INSTALL_FOLDER%
  - ps: Push-AppveyorArtifact $Env:ARTIFACT
  - cd ..

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
